apiVersion: my.net/v1alpha1
kind: EKS
metadata:
  name: c001-cluster001-dev-uw2-usa
  namespace: "cluster001-comd-"
  labels:
    k8s.home.com/pod-identity: "enable"
    k8s.home.com/cni: "vpc"
    k8s.home.com/coredns: "ga"
    k8s.home.com/cluster-class: "kubernetes-runtime"
    k8s.home.com/hostedZone: "c001.cluster001.con.dev.uw2.aws.usa.home.com"
    k8s.home.com/keda: "enable"
    k8s.home.com/serviceMesh: "istio"
    k8s.home.com/securityzone: "comd"
    k8s.home.com/platform-apps: "enable"
    k8s.home.com/cluster-group: "con"
spec:
  project: "cluster001-comd-"
  moniker: "cluster001-c-uw2"
  environment: development
  securityZone: comd
  clusterClass: kubernetes-runtime
  account:
    id: ""
  region: "us-west-2"
  
